### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by johuder33** [GuillaumeCisco/redux-sagas-injector#1]
Using the current version of your package `0.2.2` I get the following error

![screen shot 2017-10-11 at 5 54 15 pm](https://user-images.githubusercontent.com/12078950/31468483-49c6b994-aeb4-11e7-8193-63b7c5d9134b.png)

This only happened with the current version `0.2.2`, but using version `0.1.0` is working

**Comment by ethanneff** [comment]
I am getting the same error

**Comment by GuillaumeCisco** [comment]
Hello @johuder33, sorry for the delay, I didn't receive the notifications about issues.

I will investigate about this in order to find a solution. `regeneratorRuntime` is present in a babel preset most of the time. I'm not sure we should include it.

**Comment by GuillaumeCisco** [comment]
@johuder33 @ethanneff 
Thanks for using redux-sagas-injector and sorry for the delay.
I've just updated the code to 0.2.3. It should work correctly now.
Tell me if you see any regression.
Thank you,
