### ISSUE TITLE
Redux >= 6.0 example not working.

### ISSUE THREAD

**Issue by Verikon** [GuillaumeCisco/redux-sagas-injector#6]
Thanks for this library, I've found great use with it.

On a new project that's using redux 6.0 and can't seem to get the example provided working:
```Uncaught TypeError: Class constructor WithInjectedReducers cannot be invoked without 'new'```

That seems to make sense to me as the withInjectedReducer decorator does export a class definition.

**Comment by Verikon** [comment]
closed - error in **my** code.

**Comment by GuillaumeCisco** [comment]
Thank you :+1
