### ISSUE TITLE
Update to a new version of redux-saga

### ISSUE THREAD

**Issue by epotockiy** [GuillaumeCisco/redux-sagas-injector#7]
Redux-saga version 1.0.0 was released https://github.com/redux-saga/redux-saga/releases/tag/v1.0.0
@GuillaumeCisco could you update injector to latest version

**Comment by GuillaumeCisco** [comment]
@epotockiy  Thanks for the update.
I see a lot of breaking changes in this new version.
Do you think upgrading will still work?
Did you try it?
If it does not, can you create a PR with related issues?

I do no have a lot of time right now to dedicate on this tool.

**Comment by epotockiy** [comment]
Hi @GuillaumeCisco
Sorry for late answer
Today i copied injector code locally (for excluding situation with two version of ``redux-saga`` library) and installed new version of ``redux-saga``
All works good, and i think no reasons to delay version upgrade
Also can you please update ``redux-reducers-injector`` in dependencies to the latest version, i know that only ReadMe file updates are included in the latest version, but still i think it will be better
If you need a **PR** for this I can create it

**Comment by GuillaumeCisco** [comment]
Thank you @epotockiy 
I will test it today with my own projects.
I think this is not a breaking change for our case.
But we need to be sure with some tests ;)

**Comment by epotockiy** [comment]
@GuillaumeCisco  Yeh, shure

**Comment by GuillaumeCisco** [comment]
FYI just came into some issues when trying to update https://github.com/redux-saga/redux-saga/issues/1733

Furthermore some modifications are needed for supporting sagas cancellation in HMR.

**Comment by GuillaumeCisco** [comment]
I've just released a new version supporting redux-saga 1.0.1 :tada:
