### ISSUE TITLE
How to support the typescript?

### ISSUE THREAD

**Issue by PitterL** [GuillaumeCisco/redux-sagas-injector#9]
When i use ts to import the module, there will eoor not index.d.ts file:

TS7016: Could not find a declaration file for module 'redux-sagas-injector'. 'D:/Users/a41450/vscode/js/reactronts/node_modules/redux-sagas-injector/lib/redux-sagas-injector.js' implicitly has an 'any' type.
  Try `npm install @types/redux-sagas-injector` if it exists or add a new declaration (.d.ts) file containing `declare module 'redux-sagas-injector';`
Version: typescript 3.7.4

Thanks.

**Comment by GuillaumeCisco** [comment]
`redux-sagas-injector` is free from typescript.
Please see this [stackoverflow answer](https://stackoverflow.com/a/50516783) for making it compatible with your code base under typescript.
